### ISSUE TITLE
Start-up error on Grails 3.1.1

### ISSUE THREAD

**Issue by crisbarredo** [kefirfromperm/grails-asynchronous-mail#52]
I'm having the following error on Grails 3.1.1 startup.

>org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'null' with class 'org.grails.config.NavigableMap$NullSafeNavigator' to class 'java.lang.Long'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToNumber(DefaultTypeTransformation.java:163) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:272) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232) ~[groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603) ~[groovy-2.4.5.jar:2.4.5]
	at grails.plugin.asyncmail.AsynchronousMailGrailsPlugin.startJobs(AsynchronousMailGrailsPlugin.groovy:109) ~[asynchronous-mail-2.0.0.RC1.jar:na]
	at grails.plugin.asyncmail.AsynchronousMailGrailsPlugin$startJobs$0.callCurrent(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154) [groovy-2.4.5.jar:2.4.5]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166) [groovy-2.4.5.jar:2.4.5]
	at grails.plugin.asyncmail.AsynchronousMailGrailsPlugin.doWithApplicationContext(AsynchronousMailGrailsPlugin.groovy:65) ~[asynchronous-mail-2.0.0.RC1.jar:na]

**Comment by kefirfromperm** [comment]
Did you have same problem with Grails 3.1.0?
Try to clean your app.Run clean task.

**Comment by Schlogen** [comment]
I'm getting this error, it's because there is no default configuration and you are relying on it being there. 
https://github.com/kefirfromperm/grails-asynchronous-mail/blob/master/src/main/groovy/grails/plugin/asyncmail/AsynchronousMailGrailsPlugin.groovy#L109

**Comment by crisbarredo** [comment]
Thanks for the reply. Would you know what causing the below error when calling the sendMail method?

`2016-03-21 07:40:46,478 [http-nio-8081-exec-9] ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoSuchMethodError: org.grails.datastore.mapping.dirty.checking.DirtyCheckable.markDirty(Ljava/lang/String;Ljava/lang/Object;)V] with root cause
java.lang.NoSuchMethodError: org.grails.datastore.mapping.dirty.checking.DirtyCheckable.markDirty(Ljava/lang/String;Ljava/lang/Object;)V
	at grails.plugin.asyncmail.AsynchronousMailMessage.setAttemptInterval(AsynchronousMailMessage.groovy) ~[asynchronous-mail-2.0.0.RC2.jar:na]
`

**Comment by kefirfromperm** [comment]
Have you clean your app?

**Comment by kefirfromperm** [comment]
Which version of the plugin do you use?

**Comment by crisbarredo** [comment]
Yes I ran grails clean. I'm using the latest asynchronous-mail:2.0.0.RC2 version.

**Comment by puneetbehl** [comment]
@crisbarredo, can you try again with adding following in `grails-app/conf/application.groovy`?
```
asynchronous.mail.default.attempt.interval=300000l       // Five minutes
asynchronous.mail.default.max.attempts.count=1
asynchronous.mail.send.repeat.interval=60000l           // One minute
asynchronous.mail.expired.collector.repeat.interval=607000l
asynchronous.mail.messages.at.once=100
asynchronous.mail.send.immediately=true
asynchronous.mail.clear.after.sent=false
asynchronous.mail.disable=false
asynchronous.mail.useFlushOnSave=true
asynchronous.mail.persistence.provider='hibernate4'      // Possible values are 'hibernate', 'hibernate4', 'mongodb'
asynchronous.mail.newSessionOnImmediateSend=false
```

**Comment by kefirfromperm** [comment]
May be it helps to add quotes around word default

asynchronous.mail."default".attempt.interval=300000l       // Five minutes
asynchronous.mail."default".max.attempts.count=1
